geo $is_ru {
    2.57.184.0/22 1;
    2.58.68.0/22 1;
    2.58.98.0/24 1;
    2.58.124.0/22 1;
    2.58.212.0/24 1;
    2.59.51.0/24 1;
    2.59.76.0/22 1;
    2.59.80.0/22 1;
    2.59.160.0/22 1;
    default 0;
} # Тут часть адресов, чтобы просто показать как это работает

server {
    listen 80;

    if ($is_ru) {
        return 302 "http://127.0.0.1:7777";
    }

    location / {
        proxy_pass http://compnet_app:8080;
    }
}

server {
    listen 7777;
    location / {
        add_header Content-Type application/json;
        return 200 '{"error": "Доступ запрещён", "message": "ВАМ СЮДА НЕЛЬЗЯ. Сорян, но ты из России."}';
    }
}