geo $ru {
    include /etc/nginx/ru.conf;
    default 0;
}

server {
    listen 80;

    if ($ru) {
        return 302 "http://127.0.0.1:7777";
    }

    location / {
        proxy_pass http://compnet_app:8080;
    }
}

server {
    listen 7777;
    location / {
        add_header Content-Type application/json;
        return 200 '{"error": "Доступ запрещён", "message": "ВАМ СЮДА НЕЛЬЗЯ. Сорян, но ты из России."}';
    }
}